# docker/docker-compose.dev.yml
# Development-specific overrides and settings

services:
  api:
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DEBUG=1
    command: >
      sh -c "pip install -r requirements.txt &&
             python -m flask run --host=0.0.0.0 --port=5000"

  server:
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - API_URL=http://api:5000
    command: >
      sh -c "npm install && npm run dev-socket"

  frontend:
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_SOCKET_URL=http://localhost:3001
    command: >
      sh -c "npm install && npm run dev" 