# src/config/docker_config.yaml
# This file contains Docker-specific configuration settings for containerizing the 3AI application.
# It is used to parameterize aspects of the Docker image and container runtime.

docker:
  # Base image to be used for the Python environment.
  base_image: "python:3.10-slim"
  # Application port exposed by the container.
  app_port: 5000
  # Environment settings for Docker containers.
  environment:
    FLASK_HOST: "0.0.0.0"
    FLASK_PORT: "5000"
    FLASK_DEBUG: "False"
    LOG_LEVEL: "INFO"
    GEMINI_API_KEY: "YOUR_GOOGLE_GEMINI_API_KEY_HERE"  # Do not hardcode in production; use Docker secrets.
  # Volumes to mount for persistent storage (e.g., logs or database files).
  volumes:
    - "./logs:/app/logs"
    - "./config:/app/config"
  # Command to run when the container starts.
  command: "python src/ui/dashboard.py"
